# Generated by Django 5.0.4 on 2024-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Berita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(blank=True, max_length=50, null=True)),
                ('berita', models.TextField(blank=True, null=True)),
                ('gambar', models.CharField(blank=True, max_length=70, null=True)),
                ('kategori', models.CharField(blank=True, max_length=15, null=True)),
                ('id_user', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dt_berita',
            },
        ),
    ]
