# Generated by Django 5.0.4 on 2024-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beritaku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Pengguna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.AlterField(
            model_name='data_berita',
            name='gambar',
            field=models.CharField(default='default_image_path.jpg', max_length=255),
        ),
    ]
