# Generated by Django 5.0.4 on 2024-06-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beritaku', '0002_data_pengguna_alter_data_berita_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('tgl_lahir', models.DateField()),
                ('nik', models.CharField(max_length=16)),
                ('alamat', models.CharField(max_length=255)),
                ('kodepos', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AlterField(
            model_name='data_berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
